# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('park_type', models.CharField(max_length=200)),
                ('park_service_area', models.CharField(max_length=200)),
                ('psa_manager', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('acreage', models.FloatField()),
                ('district', models.IntegerField()),
                ('park_id', models.IntegerField(db_index=True)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('size', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParkAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=200)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks_discovery.Park')),
            ],
        ),
        migrations.CreateModel(
            name='ParkSimilarityRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_value', models.IntegerField(default=0)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parks_discovery.Park')),
                ('similar_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='parks_discovery.Park')),
            ],
        ),
    ]
