# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='park_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
