# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_discovery', '0002_auto_20160305_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='district',
            field=models.IntegerField(null=True),
        ),
    ]
