# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_discovery', '0004_auto_20160305_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='parksimilarityranking',
            name='similarity_value',
            field=models.FloatField(default=0),
        ),
    ]
